/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OrderWorkRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Snehal
 */
public class PatientTransfusionRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private Enterprise enterprise;
    private Organization patientOrg;
    private UserAccount userAcc;
    private Patient patient;
    private Patient updatedPatient;
    private UserAccount updatedPatientUserAccount;
    boolean transfusionNeeded = false;
    int plateletUnits = 0;
    int plasmaBloodUnits = 0;
    int redCellsUnits = 0;

    /**
     * Creates new form PatientTransfusionRequestsJPanel
     */
    public PatientTransfusionRequestJPanel(JPanel userProcessContainer, EcoSystem business, Enterprise enterprise, Organization patientOrg, UserAccount userAcc, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.enterprise = enterprise;
        this.patientOrg = patientOrg;
        this.userAcc = userAcc;
        this.patient = patient;
        updatedPatient = this.patient;

        if (patient.getPatientDiagnosis() != null && !patient.getPatientDiagnosis().isEmpty()) {
            updateJButton.setEnabled(false);
        }
        populateUserDetails();
    }

    private void populateUserDetails() {
        nameJTextField.setText(patient.getPatientName());
        patientGenderJTextField.setText(patient.getPatientGender());
        dateOfBirthJTextField.setText(patient.getPatientDOB().toString());
        bloodGroupJTextField.setText(patient.getPatientBloodType());
        patientLowBPJTextField.setText(patient.getPatientLowBP().toString());
        patientHighBPJTextField.setText(patient.getPatientHighBP().toString());
        patientHeartRateJTextField.setText(patient.getPatientHeartRate().toString());
        patientTemperatureJTextField.setText(patient.getPatientTemperature().toString());
        assignStaffJTextField.setText(patient.getAssignedStaff().getName());

        if (patient.getPatientDiagnosis() != null) {
            diagnosisJTextField.setText(patient.getPatientDiagnosis());
        } else {
            diagnosisJTextField.setText("");
        }

        if (patient.getPatientTreatment() != null) {
            treatmentJTextField.setText(patient.getPatientTreatment());
        } else {
            treatmentJTextField.setText("");
        }

        if (patient.isTransfusionNeeded() == true) {
            transfusionNeededjCheckBox.setSelected(true);
            redCellsUnitsJComboBox.setEnabled(true);
            plateletUnitsJComboBox.setEnabled(true);
            plasmaUnitsJComboBox.setEnabled(true);
        } else {
            transfusionNeededjCheckBox.setSelected(false);
            redCellsUnitsJComboBox.setEnabled(false);
            plateletUnitsJComboBox.setEnabled(false);
            plasmaUnitsJComboBox.setEnabled(false);
        }

        if (patient.getPlateletUnits() != 0) {
            plateletUnitsJComboBox.setSelectedItem(Integer.toString(patient.getPlateletUnits()));
        } else {
            plateletUnitsJComboBox.setSelectedItem(0);
        }

        if (patient.getPlasmaUnits() != 0) {
            plasmaUnitsJComboBox.setSelectedItem(Integer.toString(patient.getPlasmaUnits()));
        } else {
            plasmaUnitsJComboBox.setSelectedItem(0);
        }

        if (patient.getRedCellsUnits() != 0) {
            redCellsUnitsJComboBox.setSelectedItem(Integer.toString(patient.getRedCellsUnits()));
        } else {
            redCellsUnitsJComboBox.setSelectedItem(0);
        }

        if (patient.getDateBloodRequired() != null) {
            dateBloodRequiredDatePicker.setDate(patient.getDateBloodRequired());
        } else {
            dateBloodRequiredDatePicker.setDate(null);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        updateJButton = new javax.swing.JButton();
        bloodGroupJTextField = new javax.swing.JTextField();
        dateOfBirthJTextField = new javax.swing.JTextField();
        patientGenderJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        patientHighBPJTextField = new javax.swing.JTextField();
        patientLowBPJTextField = new javax.swing.JTextField();
        patientHeartRateJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        patientTemperatureJTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        assignStaffJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        diagnosisJTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        treatmentJTextField = new javax.swing.JTextField();
        transfusionNeededjCheckBox = new javax.swing.JCheckBox();
        redCellsUnitsJComboBox = new javax.swing.JComboBox();
        plasmaUnitsJComboBox = new javax.swing.JComboBox();
        plateletUnitsJComboBox = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dateBloodRequiredDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backJButton.setForeground(new java.awt.Color(51, 0, 51));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Patient Details & Vitals");

        jLabel2.setText("Patient Name");

        nameJTextField.setEditable(false);

        jLabel4.setText("Gender");

        jLabel5.setText("Date of Birth");

        jLabel8.setText("Blood Group");

        updateJButton.setForeground(new java.awt.Color(51, 0, 51));
        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        bloodGroupJTextField.setEditable(false);

        dateOfBirthJTextField.setEditable(false);

        patientGenderJTextField.setEditable(false);

        jLabel11.setText("Low BP");

        jLabel12.setText("High BP");

        patientHighBPJTextField.setToolTipText("Enter numeric value");

        patientLowBPJTextField.setToolTipText("Enter numeric value");

        patientHeartRateJTextField.setToolTipText("Enter numeric value");

        jLabel13.setText("Heart Rate");

        jLabel14.setText("Temperature (F)");

        patientTemperatureJTextField.setToolTipText("Enter numeric value");

        jLabel16.setText("Assigned Staff");

        assignStaffJTextField.setEditable(false);

        jLabel15.setText("Diagnosis");

        diagnosisJTextField.setToolTipText("enter numeric value");

        jLabel18.setText("Treatment");

        transfusionNeededjCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        transfusionNeededjCheckBox.setText("Blood Transfusion Needed");
        transfusionNeededjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfusionNeededjCheckBoxActionPerformed(evt);
            }
        });

        redCellsUnitsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        plasmaUnitsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        plateletUnitsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel17.setText("Platelet Units");

        jLabel19.setText("Date Required");

        jLabel20.setText("Red Cells Units");

        jLabel21.setText("Plasma Units");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(assignStaffJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateBloodRequiredDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientGenderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateOfBirthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientLowBPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientHighBPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientHeartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patientTemperatureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bloodGroupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(diagnosisJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(treatmentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(redCellsUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(plasmaUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(plateletUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(208, 208, 208))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(transfusionNeededjCheckBox)))))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(963, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(dateOfBirthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(patientGenderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18))
                    .addComponent(treatmentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(bloodGroupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(patientLowBPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(patientHighBPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientHeartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(patientTemperatureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(transfusionNeededjCheckBox)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redCellsUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plateletUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plasmaUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assignStaffJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(dateBloodRequiredDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel15))
                            .addComponent(diagnosisJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addContainerGap(634, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewPatientsAssignedJPanel vpajp = (ViewPatientsAssignedJPanel) component;
        vpajp.populatePatientTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        Double lowBP = Double.parseDouble(patientLowBPJTextField.getText());
        if (lowBP == null || patientLowBPJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter patient's low blood pressure !");
            return;
        }
        Double highBP = Double.parseDouble(patientHighBPJTextField.getText());
        if (highBP == null || patientHighBPJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter patient's high blood pressure !");
            return;
        }
        Double heartRate = Double.parseDouble(patientHeartRateJTextField.getText());
        if (heartRate == null || patientHeartRateJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter patient's heart rate !");
            return;
        }
        Double temperature = Double.parseDouble(patientTemperatureJTextField.getText());
        if (temperature == null || patientTemperatureJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter patient's temperature !");
            return;
        }
        String diagnosis = diagnosisJTextField.getText();
        if (diagnosis == null || diagnosis.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter diagnosis report for patient !");
            return;
        }
        String treatment = treatmentJTextField.getText();
        if (treatment == null || treatment.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter decided treatment for patient !");
            return;
        }

        
        Date dateBloodRequired = new Date();
        if (transfusionNeededjCheckBox.isSelected()) {
            transfusionNeeded = true;
            plateletUnits = Integer.parseInt((String) plateletUnitsJComboBox.getSelectedItem());
            plasmaBloodUnits = Integer.parseInt((String) plasmaUnitsJComboBox.getSelectedItem());
            redCellsUnits = Integer.parseInt((String) redCellsUnitsJComboBox.getSelectedItem());
            if (redCellsUnits == 0 && plateletUnits == 0 && plasmaBloodUnits == 0) {
                JOptionPane.showMessageDialog(null, "Please select number of blood units required !");
                return;
            }
            Date today = new Date();
            dateBloodRequired = dateBloodRequiredDatePicker.getDate();
            if (dateBloodRequired == null || dateBloodRequired.before(today)) {
                JOptionPane.showMessageDialog(null, "Please select today or a future date !");
                return;
            }
        }

        for (UserAccount patientUserAcc : patientOrg.getUserAccountDirectory().getUserAccountList()) {

            if (patient.getPatientName().equals(patientUserAcc.getPatient().getPatientName()) && patient.getPatientAdmitDate().equals(patientUserAcc.getPatient().getPatientAdmitDate()) && patient.getPatientDOB().equals(patientUserAcc.getPatient().getPatientDOB()) && patient.getPatientGender().equals(patientUserAcc.getPatient().getPatientGender()) && patient.getPatientBloodType().equals(patientUserAcc.getPatient().getPatientBloodType()) && patient.getPatientContact().equals(patientUserAcc.getPatient().getPatientContact())) {
                updatedPatientUserAccount = patientUserAcc;
            }
        }

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org.getPatientDirectory().getPatientList() != null && org.getPatientDirectory().getPatientList().contains(updatedPatient)) {
                org.getPatientDirectory().getPatientList().remove(updatedPatient);
                org.getUserAccountDirectory().getUserAccountList().remove(updatedPatientUserAccount);

                updatedPatient.setPatientLowBP(lowBP);
                updatedPatient.setPatientHighBP(highBP);
                updatedPatient.setPatientHeartRate(heartRate);
                updatedPatient.setPatientTemperature(temperature);
                updatedPatient.setPatientDiagnosis(diagnosis);
                updatedPatient.setPatientTreatment(treatment);
                updatedPatient.setTransfusionNeeded(transfusionNeeded);
                updatedPatient.setPlateletUnits(plateletUnits);
                updatedPatient.setPlasmaUnits(plasmaBloodUnits);
                updatedPatient.setRedCellsUnits(redCellsUnits);
                updatedPatient.setDateBloodRequired(dateBloodRequired);
                if (transfusionNeeded) {
                    updatedPatient.setPatientStatus("Blood Transfusion Requested");
                } else {
                    updatedPatient.setPatientStatus("Blood Transfusion Not Requested");
                }              

                updatedPatientUserAccount.setPatient(updatedPatient);
                
                org.getPatientDirectory().getPatientList().add(updatedPatient);
                org.getUserAccountDirectory().getUserAccountList().add(updatedPatientUserAccount);
                
                if (transfusionNeeded) {
                    OrderWorkRequest workRequest = new OrderWorkRequest();
                    workRequest.setPatient(updatedPatientUserAccount);
                    workRequest.setDoctor(userAcc);
                    workRequest.setHospitalEnterprise(enterprise);
                    workRequest.setRedCellsUnits(updatedPatient.getRedCellsUnits());
                    workRequest.setPlateletUnits(updatedPatient.getPlateletUnits());
                    workRequest.setPlasmaUnits(updatedPatient.getPlasmaUnits());
                    workRequest.setOrderStatus("Blood Transfusion Requested");
                    if (business.getWorkQueue() == null) {
                        WorkQueue workQueue = new WorkQueue();
                        business.setWorkQueue(workQueue);
                    }
                    business.getWorkQueue().getWorkRequestList().add(workRequest);
                    JOptionPane.showMessageDialog(null, "Saved patient diagnosis & treatment ! Placed a request for blood transfusion !");
                    updateJButton.setEnabled(false);
                    return;
                } else {
                    JOptionPane.showMessageDialog(null, "Saved patient diagnosis & treatment !");
                    updateJButton.setEnabled(false);
                    return;
                }
                
            }
        }
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void transfusionNeededjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfusionNeededjCheckBoxActionPerformed
        if(transfusionNeededjCheckBox.isSelected()) {
            transfusionNeeded = true;
            redCellsUnitsJComboBox.setEnabled(transfusionNeeded);
            plateletUnitsJComboBox.setEnabled(transfusionNeeded);
            plasmaUnitsJComboBox.setEnabled(transfusionNeeded);
        }
    }//GEN-LAST:event_transfusionNeededjCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assignStaffJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bloodGroupJTextField;
    private org.jdesktop.swingx.JXDatePicker dateBloodRequiredDatePicker;
    private javax.swing.JTextField dateOfBirthJTextField;
    private javax.swing.JTextField diagnosisJTextField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField patientGenderJTextField;
    private javax.swing.JTextField patientHeartRateJTextField;
    private javax.swing.JTextField patientHighBPJTextField;
    private javax.swing.JTextField patientLowBPJTextField;
    private javax.swing.JTextField patientTemperatureJTextField;
    private javax.swing.JComboBox plasmaUnitsJComboBox;
    private javax.swing.JComboBox plateletUnitsJComboBox;
    private javax.swing.JComboBox redCellsUnitsJComboBox;
    private javax.swing.JCheckBox transfusionNeededjCheckBox;
    private javax.swing.JTextField treatmentJTextField;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
