/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Donor.Donor;
import Business.Donor.DonorDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ManageDonorsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private OrganizationDirectory organizationDir;
     
    public ManageDonorsJPanel(JPanel userProcessContainer,Enterprise enterprise,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateTable();
    }
    
    public void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            if(organization.getName().equals("Donor Organization")) {
                organizationJComboBox.addItem(organization);
            }
        }
    }
    
   
    
    public void populateRoleComboBox(Organization organization) {
        roleJComboBox.removeAllItems();
        if (organization != null) {
            for (Role role : organization.getSupportedRole()) {
                roleJComboBox.addItem(role);
            }
        }
    }
    
    
    public void populateTable()
    {
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);
        for (Organization organization : organizationDir.getOrganizationList()) {
            for (UserAccount userAcc : organization.getUserAccountDirectory().getUserAccountList()) {
                if (userAcc.getDonor()!= null) {
                    Object[] row = new Object[3];
                    row[0] = userAcc.getDonor().getDonorID();
                    row[1] = userAcc.getDonor().getDonorName();
                    row[2] = userAcc.getRole();
                    
                    model.addRow(row);
                }
            }
        }
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dNameJTestFeild = new javax.swing.JTextField();
        dUserNameJTextFeild = new javax.swing.JTextField();
        CreateDJBtn = new javax.swing.JButton();
        BackJBtn = new javax.swing.JButton();
        passwordJPasswordField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        roleJComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 0, 51));
        setLayout(null);

        jScrollPane1.setForeground(new java.awt.Color(51, 0, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Role"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 580, 90);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Donor Information");
        add(jLabel1);
        jLabel1.setBounds(310, 10, 210, 28);

        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Name:");
        add(jLabel2);
        jLabel2.setBounds(20, 180, 70, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Username:");
        add(jLabel3);
        jLabel3.setBounds(20, 220, 80, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Password:");
        add(jLabel4);
        jLabel4.setBounds(20, 260, 80, 20);
        add(dNameJTestFeild);
        dNameJTestFeild.setBounds(120, 180, 170, 30);
        add(dUserNameJTextFeild);
        dUserNameJTextFeild.setBounds(120, 220, 170, 30);

        CreateDJBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateDJBtn.setForeground(new java.awt.Color(51, 0, 51));
        CreateDJBtn.setText("Create Donor");
        CreateDJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDJBtnActionPerformed(evt);
            }
        });
        add(CreateDJBtn);
        CreateDJBtn.setBounds(410, 350, 150, 30);

        BackJBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackJBtn.setForeground(new java.awt.Color(51, 0, 51));
        BackJBtn.setText("<<BACK");
        BackJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackJBtnActionPerformed(evt);
            }
        });
        add(BackJBtn);
        BackJBtn.setBounds(40, 350, 110, 30);
        add(passwordJPasswordField);
        passwordJPasswordField.setBounds(120, 260, 170, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("Role:");
        add(jLabel11);
        jLabel11.setBounds(350, 230, 70, 20);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("Organization:");
        add(jLabel12);
        jLabel12.setBounds(350, 180, 110, 20);

        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox);
        organizationJComboBox.setBounds(460, 180, 190, 30);

        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(roleJComboBox);
        roleJComboBox.setBounds(460, 230, 190, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/drop (1) (1) (1).jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(51, 0, 51)));
        add(jLabel8);
        jLabel8.setBounds(710, 30, 121, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void BackJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_BackJBtnActionPerformed

    private void CreateDJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDJBtnActionPerformed
        // TODO add your handling code here:
        
        
            Organization organization = (Organization) organizationJComboBox.getSelectedItem();
            Role role = (Role) roleJComboBox.getSelectedItem();
            
            String name = dNameJTestFeild.getText();
            String userName = dUserNameJTextFeild.getText();
            String password = String.valueOf(passwordJPasswordField.getPassword());

            DonorDirectory donorDir = new DonorDirectory();
            Donor donor = donorDir.createDonor(name);
            organization.getDonorDirectory().createDonor(name);
            organization.getUserAccountDirectory().createUserAccount(userName, password, null, null, donor, role);
             

            populateTable();
        
    }//GEN-LAST:event_CreateDJBtnActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
         
         populateRoleComboBox((Organization) organizationJComboBox.getSelectedItem());
    }//GEN-LAST:event_organizationJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackJBtn;
    private javax.swing.JButton CreateDJBtn;
    private javax.swing.JTextField dNameJTestFeild;
    private javax.swing.JTextField dUserNameJTextFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JComboBox roleJComboBox;
    // End of variables declaration//GEN-END:variables
}
