/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Snehal
 */
public class PatientAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAcc;
    /**
     * Creates new form PatientAreaJPanel
     */
    public PatientAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAcc = userAcc;
        hospitalNameLabel.setText(enterprise.getName());
        patientNameLabel.setText(userAcc.getPatient().getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookAppointmentJButton = new javax.swing.JButton();
        viewPersonalDetailsJButton = new javax.swing.JButton();
        patientNameLabel = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        viewHistoryJButton = new javax.swing.JButton();
        helloLabel1 = new javax.swing.JLabel();
        hospitalNameLabel = new javax.swing.JLabel();

        bookAppointmentJButton.setText("Book an Appointment");
        bookAppointmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAppointmentJButtonActionPerformed(evt);
            }
        });

        viewPersonalDetailsJButton.setText("View Personal Details");
        viewPersonalDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonalDetailsJButtonActionPerformed(evt);
            }
        });

        patientNameLabel.setText("<value>");

        helloLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helloLabel.setText("Hello,");

        viewHistoryJButton.setText("View History");
        viewHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryJButtonActionPerformed(evt);
            }
        });

        helloLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        helloLabel1.setText("Hospital");

        hospitalNameLabel.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPersonalDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookAppointmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hospitalNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(helloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalNameLabel))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLabel)
                    .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(viewPersonalDetailsJButton)
                .addGap(18, 18, 18)
                .addComponent(bookAppointmentJButton)
                .addGap(18, 18, 18)
                .addComponent(viewHistoryJButton)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookAppointmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAppointmentJButtonActionPerformed
        PatientBookAppointmentJPanel patientBookAppointmentJPanel = new PatientBookAppointmentJPanel(userProcessContainer, enterprise, userAcc);
        userProcessContainer.add("patientBookAppointmentJPanel", patientBookAppointmentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_bookAppointmentJButtonActionPerformed

    private void viewPersonalDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonalDetailsJButtonActionPerformed
        PatientPersonalDetailsJPanel patientPersonalDetailsJPanel = new PatientPersonalDetailsJPanel(userProcessContainer, enterprise, userAcc);
        userProcessContainer.add("patientPersonalDetailsJPanel", patientPersonalDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPersonalDetailsJButtonActionPerformed

    private void viewHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryJButtonActionPerformed
        PatientViewHistoryJPanel patientViewHistoryJPanel = new PatientViewHistoryJPanel(userProcessContainer, enterprise, userAcc);
        userProcessContainer.add("patientViewHistoryJPanel", patientViewHistoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookAppointmentJButton;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel helloLabel1;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JButton viewHistoryJButton;
    private javax.swing.JButton viewPersonalDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
