/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BloodBankStaffRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class BloodBankStaffAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAcc;
    public BloodBankStaffAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAcc = userAcc;
        bloodbankNameLabel.setText(enterprise.getName());
        bloodBankStaffNameLabel.setText(userAcc.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bloodbankNameLabel = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        bloodBankStaffNameLabel = new javax.swing.JLabel();
        BloodDonationjButton = new javax.swing.JButton();
        updatePswdjBtn = new javax.swing.JButton();

        bloodbankNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bloodbankNameLabel.setText("<value>");

        helloLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        helloLabel.setText("Hello,");

        bloodBankStaffNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bloodBankStaffNameLabel.setText("<value>");

        BloodDonationjButton.setText("View Donors and Schedule Blood Donation");
        BloodDonationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodDonationjButtonActionPerformed(evt);
            }
        });

        updatePswdjBtn.setText("Update Password");
        updatePswdjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePswdjBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bloodbankNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bloodBankStaffNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(BloodDonationjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(updatePswdjBtn)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(bloodbankNameLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodBankStaffNameLabel)
                    .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(BloodDonationjButton)
                .addGap(38, 38, 38)
                .addComponent(updatePswdjBtn)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BloodDonationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodDonationjButtonActionPerformed
        // TODO add your handling code here:
        ViewDonorsJPanel viewDonorJPanel = new ViewDonorsJPanel(userProcessContainer, enterprise, organization, userAcc);
        userProcessContainer.add("viewDonorJPanel",viewDonorJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_BloodDonationjButtonActionPerformed

    private void updatePswdjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePswdjBtnActionPerformed
        // TODO add your handling code here:
        BloodBankStaffPswdUpdateJPanel bloodBankStaffPswdUpdateJPanel = new BloodBankStaffPswdUpdateJPanel(userProcessContainer, organization, userAcc);
        userProcessContainer.add("bloodBankStaffPswdUpdateJPanel", bloodBankStaffPswdUpdateJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updatePswdjBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BloodDonationjButton;
    private javax.swing.JLabel bloodBankStaffNameLabel;
    private javax.swing.JLabel bloodbankNameLabel;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JButton updatePswdjBtn;
    // End of variables declaration//GEN-END:variables
}
