/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DonorRole;

import Business.Donor.Donor;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class DonorPersonalDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAcc;
    private Donor oldDonor;
    private Donor updatedDonor;
    private UserAccount updatedUserAccount;

    public DonorPersonalDetailsJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAcc = userAcc;
        oldDonor = userAcc.getDonor();
        updatedUserAccount = this.userAcc;
        populateUserDetails();
    }
    
    private void populateUserDetails() {
        nameJTextField.setText(oldDonor.getDonorName());
        usernameJTextField.setText(userAcc.getUsername());

        if (oldDonor.getContact() != null) {
            contactNoJTextField.setText(oldDonor.getContact().toString());
        } else {
            contactNoJTextField.setText("");
        }
        

        if (oldDonor.getGender() != null) {
            genderJComboBox.setSelectedItem(oldDonor.getGender());
        } else {
            genderJComboBox.setSelectedItem("");
        }

        if (oldDonor.getDOB() != null) {
            DOBDatePicker.setDate(oldDonor.getDOB());
        } else {
            DOBDatePicker.setDate(null);
        }

        if (oldDonor.getDonorBloodType() != null) {
            bloodGroupJComboBox.setSelectedItem(oldDonor.getDonorBloodType());
        } else {
            bloodGroupJComboBox.setSelectedItem("");
        }
        
        if (oldDonor.getDonorHeight() != null)
        {
            HtjTextField.setText(oldDonor.getDonorWeight().toString());
        }
        else
        {
            HtjTextField.setText("");
        }
        
        if (oldDonor.getDonorWeight() != null)
        {
            WeightjTextField.setText(oldDonor.getDonorWeight().toString());
        }
        else
        {
            WeightjTextField.setText("");
        }
    }
    
    private boolean ContactPatternCorrect() {

        Pattern p = Pattern.compile("^[0][1-9]\\d{9}$|^[1-9]\\d{9}$");
        Matcher m = p.matcher(contactNoJTextField.getText());
        boolean b = m.matches();
        return b;
    }
    
    private boolean HeightPatternCorrect() {

        String ht = HtjTextField.getText();
//        Pattern p = Pattern.compile("^[0-9]+\\.[0-9]+$");
        Pattern p = Pattern.compile("^[0-9]+$");
        Matcher m = p.matcher(ht);
        boolean b = m.matches();
        return b;
    }
    
    private boolean WeightPatternCorrect() {

        String ht = HtjTextField.getText();
//        Pattern p = Pattern.compile("^[0-9]+\\.[0-9]+$");
        Pattern p = Pattern.compile("^[0-9]+$");
        Matcher m = p.matcher(ht);
        boolean b = m.matches();
        return b;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        genderJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DOBDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        contactNoJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bloodGroupJComboBox = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        changePasswordJButton = new javax.swing.JButton();
        SaveJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        HtjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        WeightjTextField = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Personal Information");

        jLabel2.setText("Name");

        nameJTextField.setEditable(false);

        jLabel4.setText("Gender");

        genderJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Male", "Female", "Other" }));

        jLabel3.setText("Username");

        usernameJTextField.setEditable(false);

        jLabel5.setText("Date of Birth");

        jLabel7.setText("Contact No.");

        contactNoJTextField.setToolTipText("enter numeric value");

        jLabel8.setText("Blood Group");

        bloodGroupJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "A RhD positive (A+)", "A RhD negative (A-)", "B RhD positive (B+)", "B RhD negative (B-)", "O RhD positive (O+)", "O RhD negative (O-)", "AB RhD positive (AB+)", "AB RhD negative (AB-)" }));

        backJButton.setForeground(new java.awt.Color(51, 0, 51));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        changePasswordJButton.setForeground(new java.awt.Color(51, 0, 51));
        changePasswordJButton.setText("Change Password");
        changePasswordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordJButtonActionPerformed(evt);
            }
        });

        SaveJButton.setForeground(new java.awt.Color(51, 0, 51));
        SaveJButton.setText("Save");
        SaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Height (cms)");

        HtjTextField.setToolTipText("Enter numeric value");

        jLabel9.setText("Weight(Kgs)");

        WeightjTextField.setToolTipText("Enter numeric value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(180, 180, 180))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(contactNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HtjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(genderJComboBox, 0, 247, Short.MAX_VALUE)
                                    .addComponent(DOBDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(bloodGroupJComboBox, 0, 247, Short.MAX_VALUE)
                                    .addComponent(WeightjTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(changePasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(DOBDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodGroupJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HtjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(WeightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePasswordJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void changePasswordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordJButtonActionPerformed
       DonorPasswordUpdateJPanel donorPasswordUpdateJPanel = new DonorPasswordUpdateJPanel(userProcessContainer, organization, userAcc);
        userProcessContainer.add("donorPasswordUpdateJPanel", donorPasswordUpdateJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_changePasswordJButtonActionPerformed

    private void SaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButtonActionPerformed
     
        String donorNo = contactNoJTextField.getText();
        
        if (donorNo == null || !ContactPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid 10 digit contact number !");
            return;
        }
        
        if (HeightPatternCorrect())
        {
            try
            {
                Double.parseDouble(HtjTextField.getText());
            }
            catch(NumberFormatException nfe)
            {
                JOptionPane.showMessageDialog(null, "Please enter valid donor's height in numbers !");
            }
            catch (Exception e)
            {
                  JOptionPane.showMessageDialog(null, "Please enter valid donor's height in numbers !");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter valid donor's height !");
        }
         /*Double height = Double.parseDouble(HtjTextField.getText());
        if (height == null || HtjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter valid donor's height !");
            return;
        }*/
         
         if (WeightPatternCorrect())
        {
            try
            {
                Double.parseDouble(WeightjTextField.getText());
            }
            catch(NumberFormatException nfe)
            {
                JOptionPane.showMessageDialog(null, "Please enter valid donor's weight in numbers !");
            }
            catch (Exception e)
            {
                  JOptionPane.showMessageDialog(null, "Please enter valid donor's weight in numbers !");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please enter valid donor's weight !");
        }
        
       /* Double weight = Double.parseDouble(WeightjTextField.getText());
        if (weight == null || WeightjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter valid patient's weight !");
            return;
        }*/
        
        String donorGender = genderJComboBox.getSelectedItem().toString();
        if (donorGender == null || donorGender.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select donor's gender !");
            return;
        }
        
        String donorBloodGroup = bloodGroupJComboBox.getSelectedItem().toString();
        if (donorBloodGroup == null || donorBloodGroup.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select donor's blood group !");
            return;
        }
        Date today = new Date();
        Date donorDOB = DOBDatePicker.getDate();
        if (donorDOB == null || donorDOB.after(today)) {
            JOptionPane.showMessageDialog(null, "Please select valid date of birth for donor !");
            return;
        }
        
        Double donorwt = Double.parseDouble(WeightjTextField.getText());
        Double donorht = Double.parseDouble(HtjTextField.getText());

        for (Donor donor: organization.getDonorDirectory().getDonorList())
        {
            if(donor.getDonorName().equals(oldDonor.getDonorName())&&
                    //donor.getDonorRegisteredDate()==null||  (donor.getDonorRegisteredDate().equals(oldDonor.getDonorRegisteredDate()))&&
                    oldDonor.getDOB() == null || (donor.getDOB().equals(oldDonor.getDOB()))&&
                    oldDonor.getGender()== null || (donor.getGender().equals(oldDonor.getGender()))&&
                    donor.getDonorBloodType()== null || (donor.getDonorBloodType().equals(oldDonor.getDonorBloodType()))&&
                    donor.getContact() == null || (donor.getContact().equals(oldDonor.getContact()))&&
                    donor.getDonorWeight() == null || (donor.getDonorWeight().equals(oldDonor.getDonorWeight()))&&
                    donor.getDonorHeight() == null || (donor.getDonorHeight().equals(oldDonor.getDonorHeight())))
            {
                updatedDonor = donor;
            }
        }
        
        organization.getDonorDirectory().getDonorList().remove(updatedDonor);
        organization.getUserAccountDirectory().getUserAccountList().remove(userAcc);
        
        updatedDonor.setContact(donorNo);
        updatedDonor.setGender(donorGender);
        updatedDonor.setDOB(donorDOB);
        updatedDonor.setDonorBloodType(donorBloodGroup);
        updatedDonor.setDonorWeight(donorwt);
        updatedDonor.setDonorHeight(donorht);
        
        updatedUserAccount.setDonor(updatedDonor);
        
        organization.getDonorDirectory().getDonorList().add(updatedDonor);
        organization.getUserAccountDirectory().getUserAccountList().add(updatedUserAccount);
         JOptionPane.showMessageDialog(null, "Saved Donor information !");
         

       
        
    }//GEN-LAST:event_SaveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DOBDatePicker;
    private javax.swing.JTextField HtjTextField;
    private javax.swing.JButton SaveJButton;
    private javax.swing.JTextField WeightjTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox bloodGroupJComboBox;
    private javax.swing.JButton changePasswordJButton;
    private javax.swing.JTextField contactNoJTextField;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
