/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabSupervisorRole;

import Business.Donor.Donor;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ExtractBloodJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization donorOrg;
    private UserAccount userAcc;
    private Donor donor;
    private Donor updatedDonor;
    private UserAccount updatedDonorUserAccount;
    private Organization LabOrg;
    public ExtractBloodJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization donorOrg, UserAccount userAcc, Donor donor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.donorOrg = donorOrg;
        this.userAcc = userAcc;
        this.donor = donor;
        updatedDonor = this.donor;
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org.getName().contains("Lab Supervisor"))
            {
                LabOrg = org;
            }
           
        }
        populateUserDetails();
        //UpdatejButton.setEnabled(false);
        
        
    }
    
  /* public void disableBtn()
   {
       String donorEligible = DonorEligibilityJTextField.getText();
         if(donorEligible == "no"||donorEligible=="NO")
        {
            
       
            UpdatejButton.setEnabled(false);
            return;
        }
        
   }*/
    
    public void populateUserDetails()
    {
        nameJTextField.setText(donor.getDonorName());
        donorGenderJTextField.setText(donor.getGender());
        bloodGroupJTextField.setText(donor.getDonorBloodType());
        dateOfBirthJTextField.setText(donor.getDOB().toString());
        contactNoJTextField.setText(donor.getContact());
        dateOfregJTextField.setText(donor.getDonorRegisteredDate().toString());
        HeightJTextField.setText(donor.getDonorHeight().toString());
        WeightJTextField.setText(donor.getDonorWeight().toString());
        HeartRateJTextField.setText(donor.getDonorHeartRate().toString());
        BloodPressJTextField.setText(donor.getDonorBP().toString());
        TempJTextField.setText(donor.getDonortemp().toString());
        AssStaffJTextField.setText(donor.getAssignedStaff().getName());
        DonorEligibilityJTextField.setText(donor.getDonorstatus());
        
        

        if (donor.getPlasmaUnits()!= 0) {
            plasmaUnitsJComboBox.setSelectedItem(Integer.toString(donor.getPlasmaUnits()));
        } else {
            plasmaUnitsJComboBox.setSelectedItem(0);
        }

        if (donor.getRBCUnits() != 0) {
            redCellsUnitsJComboBox.setSelectedItem(Integer.toString(donor.getRBCUnits()));
        } else {
            redCellsUnitsJComboBox.setSelectedItem(0);
        }
        
        if(donor.getPlatelettUnits() !=0)
        {
            platelettUnitsJComboBox.setSelectedItem(Integer.toString(donor.getPlatelettUnits()));
        }
        else
        {
            platelettUnitsJComboBox.setSelectedItem(0);
        }

        if (donor.getExpiry() != null) {
            ExpiryDatePicker.setDate(donor.getExpiry());
        } else {
            ExpiryDatePicker.setDate(null);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        donorGenderJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bloodGroupJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateOfBirthJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        contactNoJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateOfregJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        HeightJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        WeightJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        HeartRateJTextField = new javax.swing.JTextField();
        TempJTextField = new javax.swing.JTextField();
        BloodPressJTextField = new javax.swing.JTextField();
        AssStaffJTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        redCellsUnitsJComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        plasmaUnitsJComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        platelettUnitsJComboBox = new javax.swing.JComboBox();
        ExpiryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel16 = new javax.swing.JLabel();
        UpdatejButton = new javax.swing.JButton();
        BackjButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        DonorEligibilityJTextField = new javax.swing.JTextField();

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Donor Details & Vitals");

        jLabel2.setText("Name");

        nameJTextField.setEditable(false);

        jLabel4.setText("Gender");

        donorGenderJTextField.setEditable(false);

        jLabel8.setText("Blood Group");

        bloodGroupJTextField.setEditable(false);

        jLabel5.setText("Date of Birth");

        dateOfBirthJTextField.setEditable(false);

        jLabel7.setText("Contact No.");

        contactNoJTextField.setEditable(false);

        jLabel3.setText("Registration Date");

        dateOfregJTextField.setEditable(false);

        jLabel1.setText("Height(cms)");

        HeightJTextField.setEditable(false);

        jLabel9.setText("Weight(Kgs)");

        WeightJTextField.setEditable(false);

        jLabel10.setText("Heart Rate");

        jLabel11.setText("BloodPressure");

        jLabel12.setText("Temparature");

        jLabel13.setText("Assigned Staff");

        HeartRateJTextField.setEditable(false);

        TempJTextField.setEditable(false);

        BloodPressJTextField.setEditable(false);

        AssStaffJTextField.setEditable(false);

        jLabel20.setText("Red Cells Units");

        redCellsUnitsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel14.setText("Plasma Units");

        plasmaUnitsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        jLabel15.setText("Platelett Units");

        platelettUnitsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));

        ExpiryDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpiryDatePickerActionPerformed(evt);
            }
        });

        jLabel16.setText("Expiry");

        UpdatejButton.setText("Update");
        UpdatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatejButtonActionPerformed(evt);
            }
        });

        BackjButton.setText(">>Back");
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Donor Eligibility");

        DonorEligibilityJTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TempJTextField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(HeightJTextField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bloodGroupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(contactNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(27, 27, 27)
                                        .addComponent(HeartRateJTextField)))
                                .addGap(253, 286, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AssStaffJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))
                                    .addComponent(BloodPressJTextField)
                                    .addComponent(donorGenderJTextField)
                                    .addComponent(dateOfBirthJTextField)
                                    .addComponent(dateOfregJTextField)
                                    .addComponent(WeightJTextField)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(ExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(redCellsUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(plasmaUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DonorEligibilityJTextField)
                                    .addGap(393, 393, 393))))))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UpdatejButton)
                        .addGap(50, 50, 50)
                        .addComponent(BackjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(platelettUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(donorGenderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGroupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateOfBirthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(dateOfregJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contactNoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(HeightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WeightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(HeartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BloodPressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TempJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(AssStaffJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(DonorEligibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(redCellsUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(plasmaUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(platelettUnitsJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatejButton)
                    .addComponent(BackjButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatejButtonActionPerformed
        // TODO add your handling code here:
       
        int plateletUnits = 0;
        int plasmaBloodUnits = 0;
        int redCellsUnits = 0;
        String donorEligible = DonorEligibilityJTextField.getText();
        Date dateBloodExpiry = new Date();
        plateletUnits = Integer.parseInt((String) platelettUnitsJComboBox.getSelectedItem());
        plasmaBloodUnits = Integer.parseInt((String) plasmaUnitsJComboBox.getSelectedItem());
        redCellsUnits = Integer.parseInt((String) redCellsUnitsJComboBox.getSelectedItem());
        
        Date today = new Date();
        dateBloodExpiry= ExpiryDatePicker.getDate();
        
        
        
        if (dateBloodExpiry == null || dateBloodExpiry.before(today))
        {
            JOptionPane.showMessageDialog(null, "Please select today or a future date !");
             return;
        }
        
        if(donorEligible == "no"||donorEligible=="NO")
        {
            UpdatejButton.setEnabled(false);
            return;
        }
        
        
         for (UserAccount donorUserAcc : donorOrg.getUserAccountDirectory().getUserAccountList())
         {
             if(donor.getDonorName().equals(donorUserAcc.getDonor().getDonorName())&&
                     donor.getGender().equals(donorUserAcc.getDonor().getGender())&&
                     donor.getDonorBloodType().equals(donorUserAcc.getDonor().getDonorBloodType())&&
                     donor.getDOB().equals(donorUserAcc.getDonor().getDOB())&&
                     donor.getContact().equals(donorUserAcc.getDonor().getContact())&&
                     donor.getDonorWeight().equals(donorUserAcc.getDonor().getDonorWeight())&&
                     donor.getDonorHeight().equals(donorUserAcc.getDonor().getDonorHeight())&&
                     donor.getDonorRegisteredDate().equals(donorUserAcc.getDonor().getDonorRegisteredDate())&&
                     donor.getDonorHeartRate().equals(donorUserAcc.getDonor().getDonorHeartRate())&&
                     donor.getDonorBP().equals(donorUserAcc.getDonor().getDonorBP())&&
                     donor.getDonortemp().equals(donorUserAcc.getDonor().getDonortemp()))
             {
                 updatedDonorUserAccount = donorUserAcc;
             }
         }
         
         for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
         {
             if (org.getDonorDirectory().getDonorList() != null && org.getDonorDirectory().getDonorList().contains(updatedDonor))
             {
                 org.getDonorDirectory().getDonorList().remove(updatedDonor);
                 org.getUserAccountDirectory().getUserAccountList().remove(updatedDonorUserAccount);
                 
                updatedDonor.setPlasmaUnits(plasmaBloodUnits);
                updatedDonor.setRBCUnits(redCellsUnits);
                updatedDonor.setExpiry(dateBloodExpiry);
                updatedDonor.setPlatelettUnits(plateletUnits);
                
                updatedDonorUserAccount.setDonor(updatedDonor);
                org.getDonorDirectory().getDonorList().add(updatedDonor);
                org.getUserAccountDirectory().getUserAccountList().add(updatedDonorUserAccount);
                JOptionPane.showMessageDialog(null, "Extracted Blood");
             }
         }
         
       
    }//GEN-LAST:event_UpdatejButtonActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewAssignedDonorsJPanel vadjp = (ViewAssignedDonorsJPanel) component;
        vadjp.populateDonorTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void ExpiryDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiryDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpiryDatePickerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssStaffJTextField;
    private javax.swing.JButton BackjButton;
    private javax.swing.JTextField BloodPressJTextField;
    private javax.swing.JTextField DonorEligibilityJTextField;
    private org.jdesktop.swingx.JXDatePicker ExpiryDatePicker;
    private javax.swing.JTextField HeartRateJTextField;
    private javax.swing.JTextField HeightJTextField;
    private javax.swing.JTextField TempJTextField;
    private javax.swing.JButton UpdatejButton;
    private javax.swing.JTextField WeightJTextField;
    private javax.swing.JTextField bloodGroupJTextField;
    private javax.swing.JTextField contactNoJTextField;
    private javax.swing.JTextField dateOfBirthJTextField;
    private javax.swing.JTextField dateOfregJTextField;
    private javax.swing.JTextField donorGenderJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox plasmaUnitsJComboBox;
    private javax.swing.JComboBox platelettUnitsJComboBox;
    private javax.swing.JComboBox redCellsUnitsJComboBox;
    // End of variables declaration//GEN-END:variables
}
