/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabSupervisorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class LabSupervisorAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAcc;
    public LabSupervisorAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAcc) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAcc = userAcc;
        BloodbankNameLabel.setText(enterprise.getName());
        LabSuperNameLabel.setText(userAcc.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BloodbankNameLabel = new javax.swing.JLabel();
        helloLabel = new javax.swing.JLabel();
        LabSuperNameLabel = new javax.swing.JLabel();
        ViewDonorsjButton = new javax.swing.JButton();
        UpdatePswjButton = new javax.swing.JButton();
        processExtractedBloodjButton = new javax.swing.JButton();

        BloodbankNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        BloodbankNameLabel.setText("<value>");

        helloLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        helloLabel.setText("Hello,");

        LabSuperNameLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabSuperNameLabel.setText("<value>");

        ViewDonorsjButton.setText("View Assigned Donors to extract blood");
        ViewDonorsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDonorsjButtonActionPerformed(evt);
            }
        });

        UpdatePswjButton.setText("Update Password ");
        UpdatePswjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePswjButtonActionPerformed(evt);
            }
        });

        processExtractedBloodjButton.setText("Process extracted blood");
        processExtractedBloodjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processExtractedBloodjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabSuperNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BloodbankNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processExtractedBloodjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewDonorsjButton)
                            .addComponent(UpdatePswjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BloodbankNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabSuperNameLabel))
                .addGap(54, 54, 54)
                .addComponent(ViewDonorsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(processExtractedBloodjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdatePswjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewDonorsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDonorsjButtonActionPerformed
        // TODO add your handling code here:
        ViewAssignedDonorsJPanel viewAssignedDonorsJPanel = new ViewAssignedDonorsJPanel(userProcessContainer, enterprise, organization, userAcc);
        userProcessContainer.add("viewAssignedDonorsJPanel", viewAssignedDonorsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_ViewDonorsjButtonActionPerformed

    private void UpdatePswjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePswjButtonActionPerformed
        // TODO add your handling code here:
        UpdatePasswordLabJPanel updatePasswordLabJPanel = new UpdatePasswordLabJPanel(userProcessContainer, organization, userAcc);
        userProcessContainer.add("updatePasswordLabJPanel", updatePasswordLabJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_UpdatePswjButtonActionPerformed

    private void processExtractedBloodjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processExtractedBloodjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processExtractedBloodjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodbankNameLabel;
    private javax.swing.JLabel LabSuperNameLabel;
    private javax.swing.JButton UpdatePswjButton;
    private javax.swing.JButton ViewDonorsjButton;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton processExtractedBloodjButton;
    // End of variables declaration//GEN-END:variables
}
